[tools]
# C/C++ Tools
cmake = "latest"
ninja = "latest"
gh = "latest"

# Go Tools
go = "latest"

# Java Tools
java = "latest"

# Python Tools
python = "3.12"
uv = "latest"

# Javascript/Typescript Tools
node = "22"
bun = "latest"

# Rust Tools
rust = "latest"

# Other CLI Tools
jq = "latest"
ripgrep = "latest"

[tools."github:neovim/neovim"]
version = "nightly"
asset_pattern = "nvim-linux-x86_64.tar.gz"


[settings]
idiomatic_version_file_enable_tools = ["python"]
